### ISSUE TITLE
Recommend movies based on watched and liked movies

### ISSUE THREAD

**Issue by daradermody** [daradermody/OverDB#41]
Not just favourited people

Use [this endpoint](https://developers.themoviedb.org/3/movies/get-movie-recommendations) to get movie recommendations based on movies, and [this endpoint](https://developers.themoviedb.org/3/discover/movie-discover) to discover movies involving certain people

**Comment by daradermody** [comment]
Done in a039e12de8bf2b31fcd83f7aee500132b7408c6e

**Comment by LauraMJ** [comment]
🥳
